apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: evil-nginx
  name: evil-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evil-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: evil-nginx
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        resources: {}
status: {}
