apiVersion: v2
appVersion: 1.0.0
description: Helm chart generico para deploy das aplicações de teste da org igordevopslabs
icon: https://pm1.narvii.com/6463/0af89cdaeea46ec0d6459b79b20102266da2e4d8_00.jpg
keywords:
- devops
- labs
name: paradis-app
sources:
- https://github.com/igordevopslabs/paradis-charts
version: 0.1.0
appVersion: main
