name: Build and Publish

on:
  push:
    branches:
      - main




jobs:
  security:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-container-scan.yml@main
    with:
      working_directory: "."
      image_name: evil-go-app
      dockerfile_path: Dockerfile
      tag: main
    secrets: inherit

